project:
  type: website

website:
  title: "2026 AIML4OS Funathon"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: https://aiml4os.github.io/funathon_slides/
        text: Introductory slides
      # - registration.qmd
      - onboarding.qmd
      - projects.qmd
      - event_info.qmd
      # - replay.qmd
      # - restitutions.qmd

format:
  html:
    theme:
      - cosmo
    toc: true



